In [3]:
import numpy as np

In [3]:
a = np.array([[1, 2], [1, 3]])
b = np.array([[2, 4], [3, 1]])

In [4]:
a

array([[1, 2],
       [1, 3]])

In [5]:
b

array([[2, 4],
       [3, 1]])

In [6]:
a*b

array([[2, 8],
       [3, 3]])

In [7]:
a*a

array([[1, 4],
       [1, 9]])

In [8]:
a**2

array([[1, 4],
       [1, 9]])

In [9]:
a/b

array([[0.5       , 0.5       ],
       [0.33333333, 3.        ]])

In [4]:
c = np.random.randint(0, 255, (10, 10))

In [5]:
c

array([[ 74, 150, 185, 132,  77,  50, 213, 142,  29, 107],
       [ 31,  52,  90,  90,  34, 105, 174,   6,  91, 178],
       [100, 174, 254,  68, 121,  50, 138, 168,  27,  43],
       [156,  37, 244, 233, 113,  29, 142, 137, 110,  99],
       [ 57, 195,  77,  37,  68, 183, 242, 109, 230, 252],
       [  9, 178, 245, 133,  54,  96, 149,  77,  87, 212],
       [  9, 185,  33, 125,  48, 210, 185, 227, 232, 135],
       [243, 183,  75,  24, 174, 128, 136,  86, 239,  77],
       [ 98, 123,   2,  52, 137,  26, 176, 251, 116, 148],
       [238,  93,  30, 153, 165, 103, 206, 146, 217,  46]])

In [6]:
from scipy import ndimage

In [8]:
filtered = ndimage.filters.gaussian_filter(c, sigma = 1)

In [9]:
filtered

array([[ 86, 113, 129, 112,  91, 102, 126, 111,  91, 100],
       [ 85, 110, 126, 109,  90,  99, 117, 104,  91, 100],
       [103, 126, 144, 126, 100,  99, 116, 112,  97,  96],
       [112, 132, 149, 134, 109, 110, 129, 131, 126, 127],
       [ 98, 127, 138, 119, 106, 124, 144, 146, 156, 172],
       [ 87, 123, 131, 110, 105, 129, 149, 152, 163, 177],
       [106, 122, 113, 100, 108, 134, 154, 163, 166, 159],
       [139, 123,  92,  87, 109, 131, 151, 165, 161, 141],
       [149, 115,  81,  88, 111, 126, 151, 167, 155, 128],
       [158, 113,  83, 101, 122, 133, 157, 170, 151, 116]])

In [10]:
filtered.shape

(10, 10)

In [11]:
0 < 4 < 5

True

In [12]:
filtered[filtered > 150] = 0
filtered

array([[ 86, 113, 129, 112,  91, 102, 126, 111,  91, 100],
       [ 85, 110, 126, 109,  90,  99, 117, 104,  91, 100],
       [103, 126, 144, 126, 100,  99, 116, 112,  97,  96],
       [112, 132, 149, 134, 109, 110, 129, 131, 126, 127],
       [ 98, 127, 138, 119, 106, 124, 144, 146,   0,   0],
       [ 87, 123, 131, 110, 105, 129, 149,   0,   0,   0],
       [106, 122, 113, 100, 108, 134,   0,   0,   0,   0],
       [139, 123,  92,  87, 109, 131,   0,   0,   0, 141],
       [149, 115,  81,  88, 111, 126,   0,   0,   0, 128],
       [  0, 113,  83, 101, 122, 133,   0,   0,   0, 116]])

In [14]:
filtered[np.logical_and(filtered > 125, filtered < 150)] = 1

In [15]:
filtered

array([[ 86, 113,   1, 112,  91, 102,   1, 111,  91, 100],
       [ 85, 110,   1, 109,  90,  99, 117, 104,  91, 100],
       [103,   1,   1,   1, 100,  99, 116, 112,  97,  96],
       [112,   1,   1,   1, 109, 110,   1,   1,   1,   1],
       [ 98,   1,   1, 119, 106, 124,   1,   1,   0,   0],
       [ 87, 123,   1, 110, 105,   1,   1,   0,   0,   0],
       [106, 122, 113, 100, 108,   1,   0,   0,   0,   0],
       [  1, 123,  92,  87, 109,   1,   0,   0,   0,   1],
       [  1, 115,  81,  88, 111,   1,   0,   0,   0,   1],
       [  0, 113,  83, 101, 122,   1,   0,   0,   0, 116]])

In [16]:
c

array([[ 74, 150, 185, 132,  77,  50, 213, 142,  29, 107],
       [ 31,  52,  90,  90,  34, 105, 174,   6,  91, 178],
       [100, 174, 254,  68, 121,  50, 138, 168,  27,  43],
       [156,  37, 244, 233, 113,  29, 142, 137, 110,  99],
       [ 57, 195,  77,  37,  68, 183, 242, 109, 230, 252],
       [  9, 178, 245, 133,  54,  96, 149,  77,  87, 212],
       [  9, 185,  33, 125,  48, 210, 185, 227, 232, 135],
       [243, 183,  75,  24, 174, 128, 136,  86, 239,  77],
       [ 98, 123,   2,  52, 137,  26, 176, 251, 116, 148],
       [238,  93,  30, 153, 165, 103, 206, 146, 217,  46]])

In [18]:
np.amax(c)

254

In [ ]:
np.mean(c)

In [ ]:
x, y, z = 0